### ISSUE TITLE
ne_download() not working properly

### ISSUE THREAD

**Issue by Mavromatika** [ropenscilabs/rnaturalearth#11]
Hi,
I discovered this package in Hadley Wickham's book, and I think it's very useful.
I've been playing with it a bit since yesterday, and it turns out that ne_download() can't download everything that's listed in the help page. 
I have tried airports, ports, railroads and they won't work (I get a 404 or a timeout error). 
The command I used is : 
ne_download(category="cultural", type="airports") 

It works fine for populated places though. 
Any idea why ?

**Comment by AndySouth** [comment]
Thankyou for the useful feedback.

The issue is because Natural Earth data aren't available for those at the default scale of 110. Changing to this should work for you :
`ne_download(category="cultural", type="airports",scale=50)`
`ne_download(category="cultural", type="airports",scale="medium")`

`?ne_download` shows a table of data availability at the different scales, but I'll try to add a warning if you try one that's not available.

**Comment by Mavromatika** [comment]
Thank you for your answer. I confirm that it works. Editing the help file would be good indeed, as the error one gets isn't very informative.

**Comment by AndySouth** [comment]
Thanks @Mavromatika. I've added a check and warning message. Can you check this works for you ?
If so I'll then close the issue.
Andy

**Comment by Mavromatika** [comment]
Is this the message ?
`In check_data_exist(scale = scale, category = category, type = type) :
  your combination of type, category, scale seem not to exist in the list of Natural Earth data so you may get a download fail message. Check ?ne_download or http://www.naturalearthdata.com/features/ to see data availability.`

**Comment by AndySouth** [comment]
Yes. Do you find that helpful? Would you suggest anything else?

**Comment by Mavromatika** [comment]
No, I think that should do. Thank you very much for your help !
